disabled_rules: # 执行时排除掉的规则
  - colon
  - comma
  - control_statement
  - missing_docs # 方法或者变量，没有添加注释
  - empty_count  # 获取Count时,没有先判断是否为空
  - identifier_name # 命名
  - opening_brace
  - void_return
  - statement_position
  - force_cast
  - mark
  - todo
  - multiple_closures_with_trailing_closure
  - unused_setter_value
  - unused_closure_parameter
  - function_parameter_count
  - trailing_whitespace
opt_in_rules: # 一些规则仅仅是可选的
  - empty_count
  - missing_docs
  # 可以通过执行如下指令来查找所有可用的规则:
  # swiftlint rules
included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
  # - Source
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Carthage
  - Pods
  # - Source/ExcludedFolder
  # - Source/ExcludedFile.swift

# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式
force_try:
  severity: warning # 显式
# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 300
use_nested_configs: true
# 可以通过一个数组同时进行隐式设置
type_body_length:
  - 300 # warning
  - 400 # error
# 或者也可以同时进行显式设置
file_length:
  warning: 500
  error: 1200
function_body_length:
  warning: 100
  error: 150
# 命名规则可以设置最小长度和最大程度的警告/错误
# 此外它们也可以设置排除在外的名字
type_name:
  min_length: 1 # 只是警告
  max_length: # 警告和错误
    warning: 100
    error: 150
  excluded: iPhone, a, b, c # 排除某个名字

variable_name:
  min_length: # 只有最小长度
    error: 1 # 只有错误
  excluded: # 排除某些名字
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle)